import type { Metadata } from "next";
import { Geist, Geist_Mono, Special_Elite } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { Dancing_Script } from "next/font/google";
import PoohThemeWrapper from "@/components/PoohThemeWrapper";

const specialElite = Special_Elite({
  weight: '400',
  subsets: ['latin'],
  variable: "--font-special-elite",
});

const dancing = Dancing_Script({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-cursive",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${dancing.variable} ${specialElite.variable}  ${geistMono.variable} antialiased`}
      >
        <PoohThemeWrapper> {children}</PoohThemeWrapper>
        <Toaster></Toaster>
      </body>
    </html>
  );
}
